<a href="https://colab.research.google.com/github/santoshrsarangi/tensorflow/blob/main/NLP/Pretrained_Word_Embeddings_GloVe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2023-06-07 02:09:26--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2023-06-07 02:09:26--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2023-06-07 02:09:27--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [2]:
!unzip -q glove.6B.zip

In [3]:
import numpy as np
path_to_glove_file = "glove.6B.100d.txt"

In [4]:
embedding_index = {}

In [5]:
with open(path_to_glove_file) as f:
  for line in f:
    word, coeff = line.split(maxsplit=1)
    coeff = np.fromstring(coeff, "f", sep=" ")
    embedding_index[word] = coeff


In [6]:
print(f"Found {len(embedding_index)} word vectors")

Found 400000 word vectors


In [7]:
!head glove.6B.100d.txt

the -0.038194 -0.24487 0.72812 -0.39961 0.083172 0.043953 -0.39141 0.3344 -0.57545 0.087459 0.28787 -0.06731 0.30906 -0.26384 -0.13231 -0.20757 0.33395 -0.33848 -0.31743 -0.48336 0.1464 -0.37304 0.34577 0.052041 0.44946 -0.46971 0.02628 -0.54155 -0.15518 -0.14107 -0.039722 0.28277 0.14393 0.23464 -0.31021 0.086173 0.20397 0.52624 0.17164 -0.082378 -0.71787 -0.41531 0.20335 -0.12763 0.41367 0.55187 0.57908 -0.33477 -0.36559 -0.54857 -0.062892 0.26584 0.30205 0.99775 -0.80481 -3.0243 0.01254 -0.36942 2.2167 0.72201 -0.24978 0.92136 0.034514 0.46745 1.1079 -0.19358 -0.074575 0.23353 -0.052062 -0.22044 0.057162 -0.15806 -0.30798 -0.41625 0.37972 0.15006 -0.53212 -0.2055 -1.2526 0.071624 0.70565 0.49744 -0.42063 0.26148 -1.538 -0.30223 -0.073438 -0.28312 0.37104 -0.25217 0.016215 -0.017099 -0.38984 0.87424 -0.72569 -0.51058 -0.52028 -0.1459 0.8278 0.27062
, -0.10767 0.11053 0.59812 -0.54361 0.67396 0.10663 0.038867 0.35481 0.06351 -0.094189 0.15786 -0.81665 0.14172 0.21939 0.58505 -0.52158 

In [8]:
sample_text = "the -0.038194 -0.24487 0.72812 -0.39961 0.083172 0.043953 -0.39141 0.3344 -0.57545 0.087459 0.28787 -0.06731 0.30906 -0.26384 -0.13231 -0.20757 0.33395 -0.33848 -0.31743 -0.48336 0.1464 -0.37304 0.34577 0.052041 0.44946 -0.46971 0.02628 -0.54155 -0.15518 -0.14107 -0.039722 0.28277 0.14393 0.23464 -0.31021 0.086173 0.20397 0.52624 0.17164 -0.082378 -0.71787 -0.41531 0.20335 -0.12763 0.41367 0.55187 0.57908 -0.33477 -0.36559 -0.54857 -0.062892 0.26584 0.30205 0.99775 -0.80481 -3.0243 0.01254 -0.36942 2.2167 0.72201 -0.24978 0.92136 0.034514 0.46745 1.1079 -0.19358 -0.074575 0.23353 -0.052062 -0.22044 0.057162 -0.15806 -0.30798 -0.41625 0.37972 0.15006 -0.53212 -0.2055 -1.2526 0.071624 0.70565 0.49744 -0.42063 0.26148 -1.538 -0.30223 -0.073438 -0.28312 0.37104 -0.25217 0.016215 -0.017099 -0.38984 0.87424 -0.72569 -0.51058 -0.52028"

In [9]:
a, b = sample_text.split(maxsplit=1)

In [10]:
b

'-0.038194 -0.24487 0.72812 -0.39961 0.083172 0.043953 -0.39141 0.3344 -0.57545 0.087459 0.28787 -0.06731 0.30906 -0.26384 -0.13231 -0.20757 0.33395 -0.33848 -0.31743 -0.48336 0.1464 -0.37304 0.34577 0.052041 0.44946 -0.46971 0.02628 -0.54155 -0.15518 -0.14107 -0.039722 0.28277 0.14393 0.23464 -0.31021 0.086173 0.20397 0.52624 0.17164 -0.082378 -0.71787 -0.41531 0.20335 -0.12763 0.41367 0.55187 0.57908 -0.33477 -0.36559 -0.54857 -0.062892 0.26584 0.30205 0.99775 -0.80481 -3.0243 0.01254 -0.36942 2.2167 0.72201 -0.24978 0.92136 0.034514 0.46745 1.1079 -0.19358 -0.074575 0.23353 -0.052062 -0.22044 0.057162 -0.15806 -0.30798 -0.41625 0.37972 0.15006 -0.53212 -0.2055 -1.2526 0.071624 0.70565 0.49744 -0.42063 0.26148 -1.538 -0.30223 -0.073438 -0.28312 0.37104 -0.25217 0.016215 -0.017099 -0.38984 0.87424 -0.72569 -0.51058 -0.52028'

In [11]:
c = np.fromstring(b, "f", sep=" ")

In [12]:
c

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [13]:
embedding_dim = 100

In [14]:
!curl -O https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.2M  100 80.2M    0     0  9338k      0  0:00:08  0:00:08 --:--:-- 16.8M


In [15]:
!tar -xf aclImdb_v1.tar.gz

In [16]:
!rm -r aclImdb/train/unsup

In [17]:
import os, pathlib, shutil, random

In [18]:
base_dir = pathlib.Path("aclImdb")
val_dir = base_dir / "val"
train_dir = base_dir / "train"

In [19]:
for category in ("pos", "neg"):
  os.makedirs(val_dir / category)
  files = os.listdir(train_dir / category)
  random.Random(1337).shuffle(files)
  num_of_val_files = int(len(files) * 0.2)

  val_files = files[-num_of_val_files:]

  for fname in val_files:
    shutil.move(train_dir / category / fname, val_dir / category / fname)

In [20]:
import tensorflow as tf
from tensorflow import keras

In [21]:
batch_size = 32

In [22]:
train_ds = keras.utils.text_dataset_from_directory("aclImdb/train", batch_size = batch_size)

Found 20000 files belonging to 2 classes.


In [23]:
val_ds = keras.utils.text_dataset_from_directory("aclImdb/val", batch_size=batch_size)

Found 5000 files belonging to 2 classes.


In [24]:
test_ds = keras.utils.text_dataset_from_directory("aclImdb/test", batch_size = batch_size)

Found 25000 files belonging to 2 classes.


In [25]:
from keras.layers import TextVectorization

In [26]:
max_length = 600
max_token = 20000

In [27]:
text_vectorization = TextVectorization(output_mode="int", max_tokens=max_token, output_sequence_length=max_length)

In [28]:
text_ds = train_ds.map(lambda x, y: x)

In [29]:
text_vectorization.adapt(text_ds)

In [67]:
int_train_ds = train_ds.map(
    lambda x, y: (text_vectorization(x), y),
    num_parallel_calls=4)


In [68]:
int_val_ds = val_ds.map(
    lambda x, y: (text_vectorization(x), y),
    num_parallel_calls=4)

In [69]:
int_test_ds = test_ds.map(
    lambda x, y: (text_vectorization(x), y),
    num_parallel_calls=4)

In [30]:
vocabulary = text_vectorization.get_vocabulary()

In [31]:
word_index = dict(zip(vocabulary, range(len(vocabulary))))

In [32]:
embedding_matrix = np.zeros((max_token, embedding_dim))

In [33]:
for word, i in word_index.items():
  if i < max_token:
    embedding_vector = embedding_index.get(word)

  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector 

In [34]:
embedding_matrix[56]

array([-1.53080001e-01,  6.31940007e-01,  6.55120015e-01, -3.07060003e-01,
       -2.39189997e-01,  1.36999995e-01, -2.98189998e-01, -1.40799999e-01,
        3.60130012e-01, -1.37950003e-01, -1.20240003e-01,  6.78100018e-03,
        7.37849995e-02, -1.61669999e-01,  2.36110002e-01, -4.01540011e-01,
       -1.88580006e-01,  3.23139995e-01, -2.65949994e-01,  3.54380012e-01,
        2.92910010e-01,  1.86499998e-01,  7.21359998e-02, -1.34680003e-01,
        3.53179991e-01,  2.44169999e-02, -5.83859980e-01, -9.12339985e-01,
        7.77840018e-02, -4.08439994e-01,  4.70679998e-01,  3.36930007e-01,
       -2.96629995e-01, -6.55890033e-02,  2.70330012e-01,  6.76530004e-01,
       -7.31109977e-02, -6.94520026e-02, -2.86309987e-01, -1.36800006e-01,
       -3.71740013e-01, -1.49450004e-01,  2.64240000e-02, -2.65749991e-01,
       -2.81100005e-01, -2.44389996e-01,  7.24330008e-01, -2.97789991e-01,
        1.35429993e-01, -1.19939995e+00,  3.18489999e-01, -3.17099988e-01,
        7.56879970e-02,  

In [47]:
embedding_index.get("hello")

array([ 0.26688  ,  0.39632  ,  0.6169   , -0.77451  , -0.1039   ,
        0.26697  ,  0.2788   ,  0.30992  ,  0.0054685, -0.085256 ,
        0.73602  , -0.098432 ,  0.5479   , -0.030305 ,  0.33479  ,
        0.14094  , -0.0070003,  0.32569  ,  0.22902  ,  0.46557  ,
       -0.19531  ,  0.37491  , -0.7139   , -0.51775  ,  0.77039  ,
        1.0881   , -0.66011  , -0.16234  ,  0.9119   ,  0.21046  ,
        0.047494 ,  1.0019   ,  1.1133   ,  0.70094  , -0.08696  ,
        0.47571  ,  0.1636   , -0.44469  ,  0.4469   , -0.93817  ,
        0.013101 ,  0.085964 , -0.67456  ,  0.49662  , -0.037827 ,
       -0.11038  , -0.28612  ,  0.074606 , -0.31527  , -0.093774 ,
       -0.57069  ,  0.66865  ,  0.45307  , -0.34154  , -0.7166   ,
       -0.75273  ,  0.075212 ,  0.57903  , -0.1191   , -0.11379  ,
       -0.10026  ,  0.71341  , -1.1574   , -0.74026  ,  0.40452  ,
        0.18023  ,  0.21449  ,  0.37638  ,  0.11239  , -0.53639  ,
       -0.025092 ,  0.31886  , -0.25013  , -0.63283  , -0.0118

In [56]:
embedding_matrix[19998]

array([ 0.36212999, -0.057183  ,  0.20284   ,  0.29765001, -0.12813   ,
        0.30408001,  0.36311001, -0.59105003,  0.22723   ,  0.13394   ,
       -0.93931001,  0.18164   ,  0.069121  ,  0.34399   ,  0.66371   ,
       -0.12345   ,  0.16924   , -0.084512  ,  0.47962001,  0.10422   ,
       -0.48026001, -0.67312002, -0.48794001, -0.069925  ,  0.12466   ,
        0.68282998,  0.56630999, -0.13163   , -0.31977999, -0.017861  ,
       -0.011326  ,  0.022833  , -0.36298999,  0.059825  ,  0.011526  ,
        0.37558001, -0.27059001, -0.20412   , -0.38496   ,  0.057481  ,
       -0.072329  ,  0.71090001, -0.067759  , -0.47817999, -0.41948   ,
       -0.10704   ,  0.33686   ,  0.0083115 , -0.040779  ,  0.65903002,
       -0.20169   ,  0.19501001, -0.05422   ,  0.33724001,  0.24067   ,
        0.2922    ,  0.17117999, -0.041984  , -0.98021001, -0.034493  ,
        0.13913   ,  0.43615001,  0.16836999, -0.096023  , -0.19801   ,
        0.61027002,  0.081777  , -0.40727001,  0.085385  , -0.45

In [60]:
embedding_layer = keras.layers.Embedding(
    max_token, embedding_dim,
    embeddings_initializer = keras.initializers.Constant(embedding_matrix),
    trainable=False,
    mask_zero=True
)

In [61]:
inputs = keras.Input(shape=(None,), dtype="int64")
embedded = embedding_layer(inputs)
x = keras.layers.Bidirectional(keras.layers.LSTM(32))(embedded)
x = keras.layers.Dropout(0.5)(x)
outputs = keras.layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)

In [73]:
model.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [74]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 embedding_2 (Embedding)     (None, None, 100)         2000000   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               34048     
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 1)                 65        
                                                                 
Total params: 2,034,113
Trainable params: 34,113
Non-trainable params: 2,000,000
______________________________________________

In [65]:
callbacks = [
    keras.callbacks.ModelCheckpoint("glove_embeddings_sequence_model.keras",
                                    save_best_only=True)
]

In [75]:
model.fit(int_train_ds, validation_data=int_val_ds, epochs=10, callbacks=callbacks)

Epoch 1/10
625/625 [==============================] - 64s 58ms/step - loss: 0.5714 - accuracy: 0.6938 - val_loss: 0.4951 - val_accuracy: 0.7728
Epoch 2/10
625/625 [==============================] - 36s 58ms/step - loss: 0.4558 - accuracy: 0.7893 - val_loss: 0.4494 - val_accuracy: 0.7834
Epoch 3/10
625/625 [==============================] - 39s 63ms/step - loss: 0.4071 - accuracy: 0.8209 - val_loss: 0.3824 - val_accuracy: 0.8316
Epoch 4/10
625/625 [==============================] - 30s 48ms/step - loss: 0.3755 - accuracy: 0.8378 - val_loss: 0.3931 - val_accuracy: 0.8224
Epoch 5/10
625/625 [==============================] - 32s 51ms/step - loss: 0.3505 - accuracy: 0.8521 - val_loss: 0.3404 - val_accuracy: 0.8516
Epoch 6/10
625/625 [==============================] - 28s 44ms/step - loss: 0.3267 - accuracy: 0.8629 - val_loss: 0.3590 - val_accuracy: 0.8374
Epoch 7/10
625/625 [==============================] - 33s 53ms/step - loss: 0.3080 - accuracy: 0.8752 - val_loss: 0.3186 - val_accuracy:

In [76]:
model = keras.models.load_model("glove_embeddings_sequence_model.keras")

In [77]:
print(f"Text accuracy: {model.evaluate(int_test_ds)[1]: .3f}")

782/782 [==============================] - 19s 21ms/step - loss: 0.2981 - accuracy: 0.8752
Text accuracy:  0.875
