<a href="https://colab.research.google.com/github/santoshrsarangi/tensorflow/blob/main/NLP/TextVectorization_Int_vs_Multi_Hot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import TextVectorization

In [49]:
text_dataset = tf.data.Dataset.from_tensor_slices(["foo", "bar", "baz"])

In [50]:
max_features = 5000

In [51]:
max_len = 4

In [52]:
#comment this section if you are trying the "multi_hot" mode. Notice the differenc when you call the model.predict or the layer directly on the data
vectorize_layer = TextVectorization(
    max_tokens=max_features,
    output_mode="int",
    output_sequence_length=max_len
)

In [53]:
#Comment this section if you are trying out the "int" mode. Notice the differenc when you call the model.predict or the layer directly on the data
vectorize_layer = TextVectorization(
    max_tokens=max_features,
    output_mode="multi_hot"
)

In [54]:
vectorize_layer.adapt(text_dataset.batch(64))

In [55]:
model = tf.keras.models.Sequential()

In [56]:
model.add(tf.keras.Input(shape=(1,), dtype=tf.string))

In [57]:
model.add(vectorize_layer)

In [58]:
input_data = [["foo qux bar"], ["qux baz"], ["foo bar baz"], ["qux qwe baz"], ["hello"]]

In [64]:

vectorize_layer(input_data)

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[1, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 0]])>

In [59]:
model.predict(input_data)

1/1 [==============================] - 0s 129ms/step


array([[1., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [60]:
vocab = ["earth", "wind", "and", "fire"]

In [61]:
vectorize_layer = TextVectorization(
    max_tokens=max_features,
    output_mode= "int",
    output_sequence_length=max_len,
    vocabulary=vocab
)

In [62]:
vectorize_layer.get_vocabulary()

['', '[UNK]', 'earth', 'wind', 'and', 'fire']

In [63]:
vectorize_layer.get_vocabulary()

['', '[UNK]', 'earth', 'wind', 'and', 'fire']