<a href="https://colab.research.google.com/github/santoshrsarangi/tensorflow/blob/main/data-api/3_Dataset_Object_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
random_numbers = np.random.normal(size=(1000,16))

In [3]:
random_numbers[0]

array([ 0.34574178, -0.20982546, -0.17469944, -0.38021277,  0.25044075,
        2.07284802,  0.59399392, -0.30308333, -0.7596228 , -1.32840107,
        1.85100534,  0.98205677,  0.45403446, -1.0691125 ,  2.01595453,
       -0.563987  ])

In [7]:
type(random_numbers)

numpy.ndarray

In [4]:
mydataset = tf.data.Dataset.from_tensor_slices(random_numbers)

In [6]:
type(mydataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [14]:
for i, element in enumerate(mydataset):

  print(element.shape)
  print(i)
  
  if i >= 1:
    break

(16,)
0
(16,)
1


In [15]:
my_batch_dataset = mydataset.batch(batch_size=32)

In [17]:
for i, element in enumerate(my_batch_dataset):

  print(element[0])
  print(i)

  if i>=1:
    break

tf.Tensor(
[ 0.34574178 -0.20982546 -0.17469944 -0.38021277  0.25044075  2.07284802
  0.59399392 -0.30308333 -0.7596228  -1.32840107  1.85100534  0.98205677
  0.45403446 -1.0691125   2.01595453 -0.563987  ], shape=(16,), dtype=float64)
0
tf.Tensor(
[ 0.67741828 -0.77987398 -2.05108096  0.15963299 -1.00437379  2.21299427
 -0.22107879  1.09716739  0.30903262 -1.23855175  0.41204567  0.02227097
  1.04466784  0.95644695  0.30724867 -1.20990964], shape=(16,), dtype=float64)
1
