<a href="https://colab.research.google.com/github/santoshrsarangi/tensorflow/blob/main/data-api/5_Tensorflow_Data_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
import os, pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [5]:
np.set_printoptions(precision=4)

In [6]:
sample_dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
sample_dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [8]:
for data in sample_dataset:
  print(data.numpy())

1
2
3
4
5
6
7
8
9
10


In [9]:
#We can also use Python iter and next to access the elements
it=iter(sample_dataset)

In [10]:
print(next(it).numpy())

1


In [11]:
#We can also use the dataset reduce function to return a single value. 
#Here's a definitio of the reduce funtion.
#reduce(
#    initial_state, reduce_func, name=None
#)

#The reduce_func is called on every element of the input 
#dataset until the dataset is exhausted, aggregating information in 
#"previous_total" (see code below)
#The initial_state argument is used for the initial value of "previous_total"

print(sample_dataset.reduce(0, lambda previous_total, data: previous_total + data).numpy())


55


In [12]:
#Question: What will be the output of the followin?
#print(sample_dataset.reduce(0, lambda previous_total, data: previous_total * data).numpy()
#How can you get the product of all elements?

# https://www.tensorflow.org/guide/data#batching_dataset_elements
# https://www.tensorflow.org/api_docs/python/tf/data/Dataset#reduce

In [13]:
tf.random.uniform([4, 10])

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.2369, 0.3125, 0.4729, 0.8274, 0.6314, 0.9101, 0.9688, 0.5641,
        0.6663, 0.6673],
       [0.0148, 0.0531, 0.1048, 0.2456, 0.4826, 0.8302, 0.3299, 0.1179,
        0.7396, 0.3606],
       [0.5728, 0.0947, 0.305 , 0.792 , 0.7397, 0.3084, 0.0127, 0.6349,
        0.9101, 0.8871],
       [0.4732, 0.4566, 0.4087, 0.628 , 0.0311, 0.009 , 0.4054, 0.3076,
        0.9635, 0.873 ]], dtype=float32)>

In [14]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))

In [15]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [16]:
tf.random.uniform([4])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.1699, 0.3421, 0.6083, 0.326 ], dtype=float32)>

In [17]:
tf.random.uniform([4, 20], maxval=10, dtype=tf.int32)

<tf.Tensor: shape=(4, 20), dtype=int32, numpy=
array([[8, 9, 2, 2, 6, 5, 1, 1, 4, 6, 0, 7, 0, 7, 3, 3, 5, 6, 8, 1],
       [8, 6, 1, 6, 4, 3, 8, 2, 4, 5, 0, 8, 7, 9, 2, 1, 9, 4, 3, 2],
       [6, 1, 7, 1, 4, 4, 3, 7, 2, 6, 8, 7, 9, 4, 7, 8, 5, 3, 7, 6],
       [7, 9, 7, 6, 6, 1, 0, 0, 8, 9, 8, 8, 1, 4, 3, 1, 0, 4, 2, 5]],
      dtype=int32)>

In [18]:
dataset2 = tf.data.Dataset.from_tensor_slices((
    tf.random.uniform([4]),
    tf.random.uniform([4, 10], maxval=10, dtype=tf.int32)
))

In [19]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(10,), dtype=tf.int32, name=None))

In [20]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(10,), dtype=tf.int32, name=None)))

In [26]:
x = tf.sparse.SparseTensor(indices=[[1],[2]], values=[3,4], dense_shape=[9])
x.values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [28]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0], [3,3]], values=[1,9], dense_shape=[3,3]))

In [31]:
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 3]), tf.int32)

In [35]:
for x in dataset1:
  print(x.numpy())

[0.2509 0.6811 0.9301 0.4916 0.5752 0.3044 0.2075 0.8756 0.3903 0.0392]
[0.7225 0.3381 0.2436 0.6865 0.1842 0.5873 0.0363 0.7419 0.9536 0.1656]
[0.1122 0.6636 0.0137 0.6327 0.4097 0.5981 0.0567 0.6935 0.711  0.9153]
[0.7216 0.9151 0.8179 0.1198 0.3411 0.041  0.2015 0.7587 0.8276 0.1443]
